import type { Metadata } from "next";

import "./globals.css";

import Providers from "@/redux/Providers";
import { ToastContainer, toast } from "react-toastify";
import { AuthProvider } from "@/context/AuthContext";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Providers>
            <html lang="en" className={cn("font-sans", geist.variable)}>
                <body>
                    <AuthProvider>
                        <ToastContainer />
                        {children}
                    </AuthProvider>
                </body>
            </html>
        </Providers>
    );
}
